export type Post = {
  handle: string;
  community: string;
  time: string;
  body: string;
  comments: number;
  likes: number;
  avatarTone: string;
};

export const posts: Post[] = [
  {
    handle: "justdan",
    community: "hi/diy",
    time: "14m",
    body: "Finally fixed the squeaky floorboard that's been annoying me for two years. stood on it this morning, why am I so lazy?",
    comments: 82,
    likes: 244,
    avatarTone: "#C9A27A",
  },
  {
    handle: "priyak2",
    community: "hi/askhifriction",
    time: "1hr",
    body: "What with the hype for sourdough? what am I missing?",
    comments: 112,
    likes: 48,
    avatarTone: "#E5B97A",
  },
  {
    handle: "jj_F1",
    community: "hi/formula1",
    time: "58m",
    body: "That was one of the best races i've seen in a while, what a banger, thoughts?",
    comments: 340,
    likes: 884,
    avatarTone: "#7AA8C9",
  },
  {
    handle: "sam_t",
    community: "hi/todayilearned",
    time: "2d",
    body: "TIL: the petrol icon on the dash of every car has an arrow next to it showing which side the fuel cap is on. I'm 38.",
    comments: 156,
    likes: 734,
    avatarTone: "#A593C2",
  },
  {
    handle: "maya_bakes",
    community: "hi/baking",
    time: "2hr",
    body: "Third loaf this month and the crumb is still too dense. what am I doing wrong?",
    comments: 67,
    likes: 44,
    avatarTone: "#8FB4A0",
  },
  {
    handle: "lena_codes",
    community: "hi/showerthoughts",
    time: "3hr",
    body: "Debugging is just staring at something you wrote until you can see it the way a stranger would",
    comments: 204,
    likes: 1200,
    avatarTone: "#9AB8D4",
  },
  {
    handle: "marcus_goat",
    community: "hi/gardening",
    time: "4hr",
    body: "Gardeners!! my courgette leaves are going yellow at the edges. its in the sun, watering every other day. is this overwatering or something missing from the soil?",
    comments: 58,
    likes: 29,
    avatarTone: "#A8C47A",
  },
  {
    handle: "timmyballhead",
    community: "hi/funny",
    time: "4hr",
    body: "I’ve just been on a once-in-a-lifetime holiday. I’ll tell you what, never again.",
    comments: 88,
    likes: 612,
    avatarTone: "#C4A07A",
  },
  {
    handle: "RobGolfs",
    community: "hi/golf",
    time: "1hr",
    body: "losing 20 yards off the tee recently and can't figure it out. nothing changed in my setup. 42 years old if that's relevant. is this just what happens now",
    comments: 94,
    likes: 51,
    avatarTone: "#C4A07A",
  },
  {
    handle: "tomscream2004",
    community: "hi/gaming",
    time: "6hr",
    body: "What are your top 5 memorable gaming moments?",
    comments: 97,
    likes: 412,
    avatarTone: "#7A9AB8",
  },
  {
    handle: "Kira_dActually",
    community: "hi/carhelp",
    time: "1hr",
    body: "clicking noise when turning left at low speed. only does it under 20mph and only turning left. any ideas before i go to a garage and get mugged",
    comments: 142,
    likes: 37,
    avatarTone: "#B4927A",
  },
  {
    handle: "Nadiar22",
    community: "hi/showerthoughts",
    time: "2d",
    body: "every recipe that says '30 minutes' includes about 25 minutes of crying",
    comments: 189,
    likes: 2100,
    avatarTone: "#C47A8F",
  },
  {
    handle: "xxBenxx",
    community: "hi/formula1",
    time: "1d",
    body: "genuinely asking: is there a better racing circuit on the calendar right now than Suzuka. i'll wait",
    comments: 278,
    likes: 504,
    avatarTone: "#8A7AB8",
  },
  {
    handle: "chloe_deb",
    community: "hi/funny",
    time: "1hr",
    body: "a golden retriever sat down outside pret and refused to move for four minutes. owner was mortified. we all clapped when he finally got up. the dog, not the owner.",
    comments: 143,
    likes: 789,
    avatarTone: "#D4B87A",
  },
  {
    handle: "Aisha4488",
    community: "hi/gaming",
    time: "4hr",
    body: "what's actually the best game of the last five years. not the most hyped. the actual best. i have a strong opinion but i want to hear yours first",
    comments: 412,
    likes: 267,
    avatarTone: "#C8A4C8",
  },
  {
    handle: "YukiS_26",
    community: "hi/todayilearned",
    time: "8hr",
    body: "tomatoes are technically a fruit, which i knew. but so is a cucumber, courgette, pepper, aubergine, and pumpkin. we've been eating fruit salad for dinner this whole time.",
    comments: 201,
    likes: 988,
    avatarTone: "#8FC4A8",
  },
  {
    handle: "JessW2",
    community: "hi/askhifriction",
    time: "2hr",
    body: "is it normal to feel sad when you finish a really good book. asking for myself. i've been staring at the wall for 20 minutes",
    comments: 312,
    likes: 1400,
    avatarTone: "#A4B8C8",
  },
  {
    handle: "oli_m",
    community: "hi/carhelp",
    time: "40m",
    body: "mechanic just said 'it's probably just a sensor' and charged me £340. is this how it works now",
    comments: 187,
    likes: 523,
    avatarTone: "#7AA8C9",
  },
  {
    handle: "Frankfaffy",
    community: "hi/baking",
    time: "1d",
    body: "unpopular opinion: croissants from a supermarket are fine and people who say otherwise have just spent too much time in France",
    comments: 441,
    likes: 302,
    avatarTone: "#D4A0B0",
  },
  {
    handle: "dan_builds",
    community: "hi/carhelp",
    time: "6hr",
    body: "temperature gauge going to max within 5 mins of driving then dropping back to normal. fan seems to be working. coolant level fine. thermostat? water pump? am I cooking my engine??",
    comments: 98,
    likes: 21,
    avatarTone: "#C9A27A",
  },
];
